Test all functions 2

diff --git a/DBMS-Moataz2 b/DBMS-Moataz2
--- a/DBMS-Moataz2
+++ b/DBMS-Moataz2
@@ -17,6 +17,10 @@
 			done
 			
 			read -p "Enter number of columns: " columnNumber
+			while ! [[ $columnNumber =~ ^[2-9]*$ ]]; do
+				echo -e "Invalid number of columns."
+				read -p "Enter number of columns: " columnNumber
+			done
 			counter=1
 			sep="|"
 			rSep="\n"
